# Generated by Django 4.1.1 on 2023-05-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboro', '0004_transactionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(through='onboro.TransactionRecord', to='onboro.book'),
        ),
    ]
